# Generated by Django 4.0.3 on 2022-12-20 17:54

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='Nederland', max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=7, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('house_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('article_number', models.CharField(default='', max_length=255)),
                ('ean', models.IntegerField(default=0)),
                ('brand', models.CharField(default='', max_length=50)),
                ('moped', models.CharField(blank=True, max_length=255, null=True)),
                ('tuning_level', models.CharField(blank=True, choices=[('Original', 'Original'), ('Stage 1', 'Stage1'), ('Stage 2', 'Stage2'), ('Stage 3', 'Stage3'), ('Stage 4', 'Stage4')], max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=30, null=True)),
                ('colour', models.CharField(max_length=40)),
                ('cylinder_displacement', models.CharField(blank=True, max_length=7, null=True)),
                ('cylinder_piston_pin', models.CharField(blank=True, max_length=7, null=True)),
                ('cylinder_bore', models.CharField(blank=True, max_length=7, null=True)),
                ('cylinder_stroke', models.CharField(blank=True, max_length=40, null=True)),
                ('cylinder_conrod_length', models.CharField(blank=True, max_length=40, null=True)),
                ('bougie_thread', models.CharField(blank=True, max_length=40, null=True)),
                ('carburetor_type', models.CharField(blank=True, max_length=10, null=True)),
                ('carburetor_diameter', models.CharField(blank=True, max_length=7, null=True)),
                ('carburetor_airfilter_connection', models.CharField(blank=True, max_length=7, null=True)),
                ('carburetor_manifold_connection', models.CharField(blank=True, max_length=7, null=True)),
                ('carburetor_choke', models.CharField(blank=True, max_length=50, null=True)),
                ('carburetor_ports', models.CharField(blank=True, max_length=255, null=True)),
                ('variator_roller_size', models.CharField(blank=True, max_length=50, null=True)),
                ('variator_roller_weight', models.CharField(blank=True, max_length=200, null=True)),
                ('variator_range', models.CharField(blank=True, choices=[('Standerd', 'Standerd'), ('Oversized', 'Oversized')], max_length=50, null=True)),
                ('clutch_diameter', models.CharField(blank=True, max_length=7, null=True)),
                ('transmission_type', models.CharField(blank=True, max_length=25, null=True)),
                ('ignition_lighting_supply', models.CharField(blank=True, choices=[('With lighting power supply', 'Yes'), ('Without lighting power supply', 'No')], max_length=50, null=True)),
                ('light_style', models.CharField(blank=True, max_length=20, null=True)),
                ('light_voltage', models.CharField(blank=True, max_length=40, null=True)),
                ('tire_width', models.CharField(blank=True, max_length=50, null=True)),
                ('tire_height', models.CharField(blank=True, max_length=50, null=True)),
                ('tire_rim_diameter', models.CharField(blank=True, max_length=50, null=True)),
                ('tire_code', models.CharField(blank=True, max_length=50, null=True)),
                ('tire_application', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category')),
                ('technical_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_details', to='product.technicaldetails')),
            ],
            options={
                'ordering': ('date_added',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('default', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='HighlightedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounted_deal', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('highlight_until', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlighted_products', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='product.address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
