# Generated by Django 4.0.3 on 2023-01-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalDetailsDutch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(default='', max_length=255)),
                ('artikel_nummer', models.CharField(default='', max_length=255)),
                ('ean', models.IntegerField(default=0)),
                ('merk', models.CharField(default='', max_length=50)),
                ('brommer', models.CharField(blank=True, max_length=255, null=True)),
                ('tuning_level', models.CharField(blank=True, choices=[('Original', 'Original'), ('Stage 1', 'Stage1'), ('Stage 2', 'Stage2'), ('Stage 3', 'Stage3'), ('Stage 4', 'Stage4')], max_length=50, null=True)),
                ('materiaal', models.CharField(blank=True, max_length=30, null=True)),
                ('kleur', models.CharField(max_length=40)),
                ('cilinderinhoud', models.CharField(blank=True, max_length=7, null=True)),
                ('pistonpen', models.CharField(blank=True, max_length=7, null=True)),
                ('boring', models.CharField(blank=True, max_length=7, null=True)),
                ('krukas_slag', models.CharField(blank=True, max_length=40, null=True)),
                ('drijfstang_lengte', models.CharField(blank=True, max_length=40, null=True)),
                ('draad_bougie', models.CharField(blank=True, max_length=40, null=True)),
                ('type_carburateur', models.CharField(blank=True, max_length=10, null=True)),
                ('diameter_carburateur', models.CharField(blank=True, max_length=7, null=True)),
                ('luchftiler_connectie', models.CharField(blank=True, max_length=7, null=True)),
                ('spruitstuk_connectie', models.CharField(blank=True, max_length=7, null=True)),
                ('choke_carburateur', models.CharField(blank=True, max_length=50, null=True)),
                ('poorten_carburateur', models.CharField(blank=True, max_length=255, null=True)),
                ('grootte_rollen_variateur', models.CharField(blank=True, max_length=50, null=True)),
                ('gewicht_rollen_variateur', models.CharField(blank=True, max_length=200, null=True)),
                ('lengte_variateur', models.CharField(blank=True, choices=[('Standaard', 'Standerd'), ('Oversized', 'Oversized')], max_length=50, null=True)),
                ('diameter_koppeling', models.CharField(blank=True, max_length=7, null=True)),
                ('type_transmissie', models.CharField(blank=True, max_length=25, null=True)),
                ('stroomtoevoer_ontsteking', models.CharField(blank=True, choices=[('With lighting power supply', 'Yes'), ('Without lighting power supply', 'No')], max_length=50, null=True)),
                ('style_lamp', models.CharField(blank=True, max_length=20, null=True)),
                ('voltage_lamp', models.CharField(blank=True, max_length=40, null=True)),
                ('breedte_band', models.CharField(blank=True, max_length=50, null=True)),
                ('hoogte_band', models.CharField(blank=True, max_length=50, null=True)),
                ('velg_diameter_band', models.CharField(blank=True, max_length=50, null=True)),
                ('code_band', models.CharField(blank=True, max_length=50, null=True)),
                ('toepassing_band', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AlterField(
            model_name='technicaldetails',
            name='variator_range',
            field=models.CharField(blank=True, choices=[('Standard', 'Standerd'), ('Oversized', 'Oversized')], max_length=50, null=True),
        ),
    ]
