# Generated by Django 4.0.3 on 2023-01-27 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_technicaldetailsdutch_remove_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='technical_details_dutch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_details_dutch', to='product.technicaldetailsdutch'),
        ),
    ]
