# Generated by Django 4.0.2 on 2022-02-04 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='SubCategory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='subcategory',
        ),
    ]
