# Generated by Django 4.0.3 on 2023-01-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_technical_details_dutch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technicaldetailsdutch',
            old_name='luchftiler_connectie',
            new_name='luchtftiler_connectie',
        ),
    ]
