# Generated by Django 4.0.3 on 2023-01-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_luchftiler_connectie_technicaldetailsdutch_luchtftiler_connectie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technicaldetailsdutch',
            old_name='luchtftiler_connectie',
            new_name='luchtfilter_connectie',
        ),
    ]
