# Generated by Django 4.0.2 on 2022-02-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_subcategory_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCategory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='category',
        ),
    ]
