# Generated by Django 4.0.3 on 2023-01-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_luchtftiler_connectie_technicaldetailsdutch_luchtfilter_connectie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicaldetailsdutch',
            name='stroomtoevoer_ontsteking',
        ),
        migrations.AddField(
            model_name='technicaldetailsdutch',
            name='lichtspoel_ontsteking',
            field=models.CharField(blank=True, choices=[('Met lichtspoel', 'Yes'), ('zonder lichtspoel', 'No')], max_length=50, null=True),
        ),
    ]
