# Generated by Django 4.0.3 on 2022-12-16 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='TechnicalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(max_length=255)),
                ('ean', models.IntegerField()),
                ('brand', models.TextField(max_length=50)),
                ('moped', models.CharField(blank=True, max_length=255, null=True)),
                ('tuning_level', models.CharField(blank=True, choices=[('Original', 'Original'), ('Stage 1', 'Stage1'), ('Stage 2', 'Stage2'), ('Stage 3', 'Stage3'), ('Stage 4', 'Stage4')], max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=30, null=True)),
                ('colour', models.CharField(max_length=40)),
                ('cylinder_displacement', models.TextField(blank=True, max_length=7, null=True)),
                ('cylinder_piston_pin', models.TextField(blank=True, max_length=7, null=True)),
                ('cylinder_bore', models.CharField(blank=True, max_length=7, null=True)),
                ('cylinder_stroke', models.CharField(blank=True, max_length=40, null=True)),
                ('cylinder_conrod_length', models.CharField(blank=True, max_length=40, null=True)),
                ('bougie_thread', models.CharField(blank=True, max_length=40, null=True)),
                ('carburetor_type', models.TextField(blank=True, max_length=10, null=True)),
                ('carburetor_diameter', models.TextField(blank=True, max_length=7, null=True)),
                ('carburetor_airfilter_connection', models.TextField(blank=True, max_length=7, null=True)),
                ('carburetor_manifold_connection', models.TextField(blank=True, max_length=7, null=True)),
                ('carburetor_choke', models.TextField(blank=True, max_length=50, null=True)),
                ('carburetor_ports', models.TextField(blank=True, max_length=255, null=True)),
                ('variator_roller_size', models.TextField(blank=True, max_length=50, null=True)),
                ('variator_roller_weight', models.TextField(blank=True, max_length=200, null=True)),
                ('variator_range', models.CharField(blank=True, choices=[('Standerd', 'Standerd'), ('Oversized', 'Oversized')], max_length=50, null=True)),
                ('clutch_diameter', models.TextField(blank=True, max_length=7, null=True)),
                ('transmission_type', models.CharField(blank=True, max_length=25, null=True)),
                ('ignition_lighting_supply', models.CharField(blank=True, choices=[('With lighting power supply', 'Yes'), ('Without lighting power supply', 'No')], max_length=50, null=True)),
                ('light_style', models.CharField(blank=True, max_length=20, null=True)),
                ('light_voltage', models.CharField(blank=True, max_length=40, null=True)),
                ('tire_width', models.TextField(blank=True, max_length=50, null=True)),
                ('tire_height', models.TextField(blank=True, max_length=50, null=True)),
                ('tire_rim_diameter', models.TextField(blank=True, max_length=50, null=True)),
                ('tire_code', models.TextField(blank=True, max_length=50, null=True)),
                ('tire_application', models.TextField(blank=True, max_length=50, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_details', to='product.product')),
            ],
        ),
    ]
