# Generated by Django 4.0.3 on 2022-12-16 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_image_name_technicaldetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicaldetails',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='technical_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_details', to='product.technicaldetails'),
        ),
        migrations.AddField(
            model_name='technicaldetails',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='technicaldetails',
            name='article_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='technicaldetails',
            name='brand',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='technicaldetails',
            name='carburetor_airfilter_connection',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='technicaldetails',
            name='carburetor_choke',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='technicaldetails',
            name='carburetor_diameter',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='technicaldetails',
            name='carburetor_manifold_connection',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='technicaldetails',
            name='carburetor_ports',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='technicaldetails',
            name='carburetor_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='technicaldetails',
            name='clutch_diameter',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='technicaldetails',
            name='cylinder_displacement',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='technicaldetails',
            name='cylinder_piston_pin',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='technicaldetails',
            name='ean',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='technicaldetails',
            name='tire_application',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='technicaldetails',
            name='tire_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='technicaldetails',
            name='tire_height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='technicaldetails',
            name='tire_rim_diameter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='technicaldetails',
            name='tire_width',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='technicaldetails',
            name='variator_roller_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='technicaldetails',
            name='variator_roller_weight',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
